CREATE TABLE printingHouse(
phId INT PRIMARY KEY IDENTITY NOT NULL,
phName NVARCHAR(60) NOT NULL,
phPhone NVARCHAR(12) NOT NULL,
phEmail NVARCHAR(64) NOT NULL,
phCountry NVARCHAR(50) NOT NULL,
phState NVARCHAR(50) NOT NULL,
phCity NVARCHAR(50) NOT NULL,
phStreet NVARCHAR(50) NOT NULL,
phHouse NVARCHAR(50) NOT NULL
);


CREATE TABLE customer(
custId INT PRIMARY KEY IDENTITY NOT NULL,
custName NVARCHAR(100) NOT NULL,
custType NVARCHAR(50) NOT NULL,
custPhone NVARCHAR(12) NOT NULL,
custEmail NVARCHAR(64) NOT NULL
);

CREATE TABLE booking(
bkId INT PRIMARY KEY IDENTITY NOT NULL,
bkNumber INT NOT NULL,
bkDateOfAdd DATE NOT NULL,
bkDateOfComplete DATE NOT NULL,
bkStatus NVARCHAR(50) NOT NULL,
fphId INT REFERENCES printingHouse (phId),
fcustId INT REFERENCES customer (custId)
);
 